### ISSUE TITLE
SRTM data download

### ISSUE THREAD

**Issue by wolfgang-ch** [wolfgang-ch/mytourbook#309]
It seems that the SRTM data download must be changed, I just found this

https://urs.earthdata.nasa.gov/
https://urs.earthdata.nasa.gov/users/new

![mt-srtm-data](https://user-images.githubusercontent.com/1283445/109414403-ff578f00-79b2-11eb-83c2-43b1d5ca4a39.png)

**Comment by FJBDev** [comment]
That explains why it hasn't been working for me (see the discussion thread [here](https://sourceforge.net/p/mytourbook/discussion/622811/thread/e42d2dd196/#34b6))

That also explains why the unit tests have been failing lately with this error:
![image](https://user-images.githubusercontent.com/25235665/109424185-e1346380-799f-11eb-8df5-e25386d35bd7.png)

**Comment by wolfgang-ch** [comment]
@FJBDev
I just found an interresting feature, when mouse is hovered above a password field, then the entered text is immediately updated in the tooltip (with a modifier listener)


![mt password field](https://user-images.githubusercontent.com/1283445/115426508-db6d3880-a200-11eb-8f3c-ebd0a3636ab3.png)

**Comment by FJBDev** [comment]
That's nice. I will try on Linux to see if it is also supported

**Comment by wolfgang-ch** [comment]
SRTM download is now working again :-)

@FJBDev @telemaxx Can you check if SRTM is also working for you?
Let me know, if the description in the SRTM data pref page could be improved.

![mt pref page srtm data](https://user-images.githubusercontent.com/1283445/115983691-01009600-a5a3-11eb-9717-9b530ad1a3b8.png)

**Comment by telemaxx** [comment]
I can try it tomorrow.

**Comment by FJBDev** [comment]
I just tested and it works for me.
Here are my observations:
- Missing "u" in "reqires"
- That sentence doesn't sound very english, I would rename it to:
"These steps are necessary in order for MyTourbook to download SRTM data"
- I would rename "Validate Download of SRTM Data" to "Validate SRTM connexion" since when I click on it, it doesn't download anything right ?

![image](https://user-images.githubusercontent.com/25235665/116002832-bbe75e80-a5b8-11eb-86ca-768cf96d0f16.png)


One last thing is that when I click on this button
![image](https://user-images.githubusercontent.com/25235665/116002889-f3560b00-a5b8-11eb-98b2-c32a8bd5bd7d.png)

It only display an error message when it fails. When successfully downloaded SRTM data, nothing is displayed and I find it confusing (did it work ? did it fail? etc....). I think it would be nice to display when successful, just like the tour-reimport, the previous elevation gain/loss and the new one
![image](https://user-images.githubusercontent.com/25235665/116002899-04068100-a5b9-11eb-8177-3edca329a0df.png)

**Comment by telemaxx** [comment]
my tests on linux mint:

i started with tour tour chart:
in the slideout i wanted to enable "show strm data" this gives me the 
crazy cinnamon error, which Frederic had reported.
maybe a problem of cinnamon, so i switched to mate.
when i now enable "show strm data" a correct window open, but behind the 
slideout:




now i bring the window to front and see the message about the missing 
username.
then i tried to follow the link to the nasa, but seems to be currently 
not available.
i will try again later this day.



next test was to "adjust Tour Values->Elevation->Set Elevation values 
from  SRTM"
i had expected the same window with the missing username for nasa.
but no window.

In the IDE i see this:



i did my test with the latest "main" branch.

BTW:
a while ago i tried to copy srtm data manually into the corresponding 
folder in MT.
i got this data from here:
https://data.opendataportal.at/dataset/dtm-europe
a german description is here:
https://www.openandromaps.org/oam-forums/topic/neues-genaueres-hoehenmodell-fuer-oesterreich
really interesting, because this precise data are LIDAR based, not from 
satellite.
this data i could use directly inside my orux maps app on my phone, but 
MT seem to have a problem with the resolution...

Thomas


Am 25.04.2021 um 19:26 schrieb FJBDev:

**Comment by telemaxx** [comment]
my tests on linux mint:

i started with tour tour chart:
in the slideout i wanted to enable "show strm data" this gives me the
crazy cinnamon error, which Frederic had reported.
maybe a problem of cinnamon, so i switched to mate.
when i now enable "show strm data" a correct window open, but behind the
slideout:

![grafik](https://user-images.githubusercontent.com/22706487/116060562-45af2e80-a682-11eb-8e1f-3b1f59d3d902.png)


now i bring the window to front and see the message about the missing
username.
then i tried to follow the link to the nasa, but seems to be currently
not available.
i will try again later this day.



next test was to "adjust Tour Values->Elevation->Set Elevation values
from  SRTM"
i had expected the same window with the missing username for nasa.
but no window.

In the IDE i see this:

![correct_altitude_did_not_show_error](https://user-images.githubusercontent.com/22706487/116060145-e2bd9780-a681-11eb-8ccd-3ea15cc4514e.PNG)


i did my test with the latest "main" branch.

BTW:
a while ago i tried to copy srtm data manually into the corresponding
folder in MT.
i got this data from here:
https://data.opendataportal.at/dataset/dtm-europe
a german description is here:
https://www.openandromaps.org/oam-forums/topic/neues-genaueres-hoehenmodell-fuer-oesterreich
really interesting, because this precise data are LIDAR based, not from
satellite.
this data i could use directly inside my orux maps app on my phone, but
MT seem to have a problem with the resolution...

Thomas

**Comment by wolfgang-ch** [comment]
> I just tested and it works for me.
> Here are my observations:
> 
>     * Missing "u" in "reqires"
> 
>     * That sentence doesn't sound very english, I would rename it to:
>       "These steps are necessary in order for MyTourbook to download SRTM data"

I will fix it

>     * I would rename "Validate Download of SRTM Data" to "Validate SRTM connexion" since when I click on it, it doesn't download anything right ?

A small file is downloaded but I will change the wording

"connexion" is this french :-)

**Comment by wolfgang-ch** [comment]
> In the IDE i see this:
> 
> ![correct_altitude_did_not_show_error](https://user-images.githubusercontent.com/22706487/116060145-e2bd9780-a681-11eb-8ccd-3ea15cc4514e.PNG)

This can happen when you zoomin during a SRTM download, the download of SRMT data at all, was not change. I also discovered similar issue when the using the SRMT map provider then the tiles have no elevation colors.

It was not my task in this excercise to fix SRTM issues except that the download of SRTM data works again.

**Comment by wolfgang-ch** [comment]
>  when i now enable "show strm data" a correct window open, but behind the
> slideout:

I fixed it in https://github.com/wolfgang-ch/mytourbook/commit/9fccac69b0997236c8d3033b9b6ec83b9373180c, can you check if it works

**Comment by telemaxx** [comment]
on linux still the same:
![grafik](https://user-images.githubusercontent.com/22706487/116100685-73f63380-a6ad-11eb-92ee-97600a8d0de8.png)

**Comment by telemaxx** [comment]
but now i am a registered nasa user...

tour chart and elevation correction is working.

**Comment by FJBDev** [comment]
> "connexion" is this french :-)

Yes, "Connexion" is french :-). I meant "Connection"

**Comment by wolfgang-ch** [comment]
> 
> 
> on linux still the same:
> ![grafik](https://user-images.githubusercontent.com/22706487/116100685-73f63380-a6ad-11eb-92ee-97600a8d0de8.png)

Fixed in https://github.com/wolfgang-ch/mytourbook/commit/8b98df516daabaf31fd1d63d1b4b8f13f8d8a1e2

**Comment by telemaxx** [comment]
ok, now its working.

But Tour import its a bit slow:
![grafik](https://user-images.githubusercontent.com/22706487/116289013-5ea70500-a792-11eb-9c20-3b8d6830d17c.png)

most of the time MT is working on STRM:
![grafik](https://user-images.githubusercontent.com/22706487/116289151-85653b80-a792-11eb-8cd0-f919f7c29058.png)

when i delete this tour and reimport it again, strm data is on disk.
than its fast.
![grafik](https://user-images.githubusercontent.com/22706487/116289754-0d4b4580-a793-11eb-9d06-33b02da09f6f.png)

**Comment by FJBDev** [comment]
> Fixed in [8b98df5](https://github.com/wolfgang-ch/mytourbook/commit/8b98df516daabaf31fd1d63d1b4b8f13f8d8a1e2)

Verified on my Linux and the crash doesn't happen with Cinnamon.
However, I also experience the slowness that Thomas mentioned.

**Comment by wolfgang-ch** [comment]
The import is slow when

- The tour chart is opened 
- SRMT data are displayed
- SRMT data are not yet downloaded

To make it more visible, download of SRTM data is now also logged in the tour log. My first import is 11 sec (with a 1 GBit internet connection :-) the second import is 1.6 sec.

![mt import with srtm download and log](https://user-images.githubusercontent.com/1283445/116364743-ceee6e80-a804-11eb-923d-ca7fe69a2df9.png)
